from google.adk.agents import Agent, SequentialAgent

red_team_agent = Agent(
    name="red_team_agent",
    instruction=(
        "You are a security researcher in the red team, and need to test an application for multiple security vulnerabilities."
        "You will be given the API documentation, and tools like curl and python script execution."
        "Your task is to bruteforce and test the API endpoints, and figure out vulnerable parts of the software."
        "You will generate a report on the security of the API and pass it to the blue team for fixing the bugs"
    ),
    model="gemini-2.5-pro"
)

blue_team_agent = Agent(
    name="red_team_agent",
    instruction=(
        "You are a security researcher in the blue team, and need to fix vulnerabilities in the software based on the report generated by the red team."
        "You will have access to the codebase, and will need to fix vulnerable parts in the code."
        "You will also raise pull requests in the codebase on GitHub after fixing those vulnerabilities"
    ),
    model="gemini-2.5-pro"
)

root_agent = Agent(
    name="root_agent",
    sub_agents=[red_team_agent, blue_team_agent],
    instruction=(
        "You are a security agent orchestrator. You have access to 2 agents, red team and blue team. You also have access to the GitHub repository"
        "The red team agent is the attacker, and should have access to the documentation of the API."
        "The blue team agent should get access to the report generated by the red team agent, and will solve the issues and send the fixes back to the repository as a pull request"
    ),
    model="gemini-2.5-flash"
)
