from google.adk.agents import LlmAgent, LoopAgent
from .red_team.tools import web_request

red_team_agent = LlmAgent(
    name="red_team_agent",
    instruction=(
        "<system>"
        "You are a security researcher in the red team, and need to test an application for multiple security vulnerabilities."
        "You will be given the API documentation, and tools like curl and python script execution."
        "Your task is to bruteforce and test the API endpoints, and figure out vulnerable parts of the software."
        "You will generate a report on the security of the API and pass it to the blue team for fixing the bugs"
        "</system>"
    ),
    model="gemini-2.5-flash",
    output_key="red_team_report",
    tools=[web_request],
)

blue_team_agent = LlmAgent(
    name="blue_team_agent",
    instruction=(
        "<system>"
        "You are a security researcher in the blue team, and need to fix vulnerabilities in the software based on the report generated by the red team."
        "You will have access to the codebase, and will need to fix vulnerable parts in the code."
        "You will also raise pull requests in the codebase on GitHub after fixing those vulnerabilities."
        "</system>"
        "This is the report generated by the red team:\n"
        "<report>{red_team_report}</report>\n"
        "Fix use the `fetch_github` tool to first setup the repository locally on a docker container"
    ),
    model="gemini-2.5-flash",
)

root_agent = LoopAgent(
    name="root_agent",
    sub_agents=[red_team_agent, blue_team_agent],
)
